### ISSUE TITLE
Window is not defined, when used with GatsbyJS

### ISSUE THREAD

**Issue by skube** [tkloht/react-video-cover#179]
Using this component with Gatsby causes a `window is not defined error` . 

Specifically, only when doing `gatsby build` does it complain. Viewing locally works great! 😀

**Comment by romanown** [comment]
i have also Window is not defined, when used server rendering on nodejs

**Comment by tkloht** [comment]
Thanks for letting me know, and sorry for the long silence. I am very bad with my GitHub notifications.
I will definitely have a look at this, Gatsby is something that i absolutely want to support (and ssr in general).

**Comment by romanown** [comment]
this need to test for server or client side into this component.

**Comment by tkloht** [comment]
yep, i guess so. would you like to give it a shot @romanown ? I'm open for a contribution.

**Comment by romanown** [comment]
I'm not much of a specialist. I cannot help. later I will try to do it. I removed from the module the area that gave the error. but it's not right to wait.

**Comment by tkloht** [comment]
no worries then, i'll take care of it.

**Comment by romanown** [comment]
I have it running without a check functions the iPhone or not.

**Comment by danvernon** [comment]
@romanown can you fork your version?

**Comment by romanown** [comment]
I have no version. I installed the module. when I discovered and localized the problem, I opened the file index.js and deleted this piece of code. I work with reactjs.

**Comment by danvernon** [comment]
ok, im trying to deploy to gatsby and everything i have tried hasnt worke

**Comment by romanown** [comment]
I don't know about GatsbyJS

**Comment by tkloht** [comment]
alright folks, i have published version 1.2.2 to make this work with gatsby. In fact i have moved the example pages to gatsby, so you can have a look over here for an example: https://github.com/tkloht/react-video-cover/blob/master/examples/src/pages/minimal.js

**Comment by romanown** [comment]
and what about that piece of code that I gave and that gave the error?

**Comment by tkloht** [comment]
I'm not sure if i understand your question @romanown .

Server-side rendering was fixed by this pr a while ago:
https://github.com/tkloht/react-video-cover/pull/176

I just didn't publish the new version correctly, that's why you still ran into this issue.
I changed the build setup a bit and changed the example pages to use gatsby to have an easy check for ssr compatibility.
