### ISSUE TITLE
Not working on iphone 12.1.4

### ISSUE THREAD

**Issue by TimMeade** [tkloht/react-video-cover#184]
So on iPhone running ios 12.1.4 this is not working.  It does work on ipad running same version.  Odd.

Confirmed with our test code and the demo at: http://tkloht.github.io/react-video-cover/background

Our test code shows first frame.    The demo just stays black.

Any ideas?

Thanks

**Comment by TimMeade** [comment]
I just confirmed it does work on android 8.1

**Comment by TimMeade** [comment]
Simple fix.   Add playsInline to the videoOptions

          autoPlay: true,
          playsInline: true,
          muted: true,

Fixes it for IOS.

**Comment by Sjarj** [comment]
The fix `playsInline: true`, on ios 12.2 dosen't work for me,  it change just my screen black to blank
