### ISSUE TITLE
not working on safari 

### ISSUE THREAD

**Issue by Sjarj** [tkloht/react-video-cover#188]
this code work on google chrome , but not in safari 
 on safari I have just a white screen
<img width="269" alt="Capture d’écran 2019-04-06 à 16 25 38" src="https://user-images.githubusercontent.com/44477769/55670819-253c8d80-5889-11e9-9a59-e7e5c5d3c93c.png">
  I use Gatsby js , there is any error in my log .

**Comment by Sjarj** [comment]
the issue come from mp4 with safari

**Comment by fhuel** [comment]
Hey @Sjarj ,  I'm experiencing the same problem
Did you solve this issue?

**Comment by Sjarj** [comment]
Hello @fhuel , I don't remember , but this is the code that  work fine on  safari 

<img width="692" alt="Capture d'écran 2019-09-11 22 00 27" src="https://user-images.githubusercontent.com/44477769/64730588-eff33600-d4df-11e9-9c51-4e270f49e600.png">

**Comment by fhuel** [comment]
It works, thanks!
