### ISSUE TITLE
Video does not plays in real mobile devices , Let's say iPhone 11 , chrome browser.

### ISSUE THREAD

**Issue by harshendraup** [tkloht/react-video-cover#202]
Video does not plays in real mobile devices , Let's say iPhone 11 , chrome browser.

**Comment by tkloht** [comment]
i noticed there were some issues with the example pages, those are fixed.
there should not be any issue with the library itself though, as it only passes options through to the video tag. On my iPhone 11 the examples work fine.
If you are trying to create a cover video like over [here](http://tkloht.github.io/react-video-cover/background), have a look at [this example](https://github.com/tkloht/react-video-cover/blob/master/examples/src/pages/background.js).

all that said, you might not need this component at all if you are building for mobile devices, the real use case is when you need to support IE11. Have you considered using [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) directly?

If you can share an example that doesn't work i'm happy to look at it. the properties you need to pass to a video tag to make it work on mobile can be a bit tricky, but i'm sure we can figure it out. Some pitfalls on mobile are: you probably want to set `playsInline`, and if you want `autoPlay` you also need `muted`.
